/**
 * Skill Generator
 * 
 * Creates skills from validated patterns.
 * Part of Learning Agent.
 */

import * as fs from 'fs/promises';
import * as path from 'path';
import { Pattern } from './detector';
import { ConfidenceResult } from './confidence';

export interface GeneratedSkill {
  name: string;
  pattern: string;
  confidence: number;
  implementation: string;
  examples: string[];
  generated: string;
  source: string;
}

export interface GeneratorResult {
  success: boolean;
  path: string;
  skill: GeneratedSkill;
  error?: string;
}

/**
 * Generate skill name from pattern
 */
export function generateSkillName(pattern: Pattern): string {
  return `auto-${pattern.name}`;
}

/**
 * Generate skill implementation from pattern
 */
export function generateImplementation(pattern: Pattern): string {
  const steps = pattern.examples.map((ex, i) => `  ${i + 1}. ${ex}`).join('\n');
  
  return `When "${pattern.action}" action is detected:
${steps || '  1. Execute standard procedure'}

This pattern was observed ${pattern.occurrences} times.
`;
}

/**
 * Format skill as markdown
 */
export function formatSkill(skill: GeneratedSkill): string {
  return `# Skill: ${skill.name}

**Generated:** ${skill.generated}
**Confidence:** ${skill.confidence}%
**Source:** ${skill.source}

---

## Pattern

${skill.pattern}

---

## Implementation

${skill.implementation}

---

## Examples

${skill.examples.map(e => `- ${e}`).join('\n')}

---

*Auto-generated by Learning Agent*
`;
}

/**
 * Generate skill from pattern
 */
export function generateSkill(
  pattern: Pattern,
  confidence: ConfidenceResult
): GeneratedSkill {
  return {
    name: generateSkillName(pattern),
    pattern: `Action: ${pattern.action}`,
    confidence: confidence.score,
    implementation: generateImplementation(pattern),
    examples: pattern.examples,
    generated: new Date().toISOString(),
    source: 'learning-agent'
  };
}

/**
 * Write skill to vault
 */
export async function writeSkill(
  skill: GeneratedSkill,
  vaultPath: string = 'vault/skills'
): Promise<GeneratorResult> {
  const filePath = path.join(vaultPath, `${skill.name}.md`);
  
  try {
    await fs.mkdir(vaultPath, { recursive: true });
    
    const content = formatSkill(skill);
    await fs.writeFile(filePath, content, 'utf-8');
    
    return {
      success: true,
      path: filePath,
      skill
    };
  } catch (error) {
    return {
      success: false,
      path: filePath,
      skill,
      error: error instanceof Error ? error.message : String(error)
    };
  }
}

/**
 * Check if skill already exists
 */
export async function skillExists(
  skillName: string,
  vaultPath: string = 'vault/skills'
): Promise<boolean> {
  try {
    await fs.access(path.join(vaultPath, `${skillName}.md`));
    return true;
  } catch {
    return false;
  }
}

// Re-export for convenience
export { Pattern } from './detector';
export { ConfidenceResult } from './confidence';
